# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - The failure occurred because the `flutter` command was not found. This suggests that Flutter is not installed or not available in the PATH.

To fix this, you need to ensure that Flutter is installed and available in the PATH. You can add the following step in your workflow file `.github/workflows/dart.yml` to install Flutter before running `flutter pub get`:


    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$PWD/flutter/bin" >> $GITHUB_PATH
        flutter doctor


Ensure this step is added before the `flutter pub get` step. This will install Flutter and make the command available.

    - name: Flutter Pub Get
      run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
